services:
  mongodb:
    image: mongo:7.0
    container_name: api-monitoring-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: monitoring_db
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - monitoring-net

volumes:
  mongodb_data:

networks:
  monitoring-net:
    driver: bridge